version: '3.1'
services:

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
    restart: always
  drupal:
    image: drupal:8-apache
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always